// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2kjcDZ9xH1-e61NzKAHdigyQdAGQhjlo',
    appId: '1:913428755218:web:48c13e08761f107986f9cb',
    messagingSenderId: '913428755218',
    projectId: 'flutter-weather-app-11738',
    authDomain: 'flutter-weather-app-11738.firebaseapp.com',
    storageBucket: 'flutter-weather-app-11738.firebasestorage.app',
    measurementId: 'G-VLBG4R4QC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB77ELg3UcpHwt3rVVEGaIeG9EEG-iGQA',
    appId: '1:913428755218:android:99b1548bee65ce3986f9cb',
    messagingSenderId: '913428755218',
    projectId: 'flutter-weather-app-11738',
    storageBucket: 'flutter-weather-app-11738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Rxwk9C3-ytzLToB0Av9u8a2_bUBsIhQ',
    appId: '1:913428755218:ios:3d9012ffb9bec86586f9cb',
    messagingSenderId: '913428755218',
    projectId: 'flutter-weather-app-11738',
    storageBucket: 'flutter-weather-app-11738.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );
}
